site_name: opzioni docs
repo_url: https://github.com/ggabriel96/opzioni
repo_name: ggabriel96/opzioni

dev_addr: 127.0.0.1:7011
docs_dir: src/
site_dir: build/

theme:
  name: material
  language: en
  icon:
    logo: octicons/terminal-24
    repo: fontawesome/brands/github
  favicon: assets/images/terminal.svg
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep purple
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  font:
    code: JetBrains Mono
    text: Inter

nav:
  - Home: index.md
  - User guide:
    - user-guide/the-basics.md
    - user-guide/customizing-programs.md

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
