site_name: opzioni docs
repo_url: https://github.com/ggabriel96/opzioni
repo_name: ggabriel96/opzioni

dev_addr: 127.0.0.1:7011
docs_dir: src/
site_dir: build/

theme:
  name: material
  language: en
  icon:
    logo: octicons/terminal-24
    repo: fontawesome/brands/github
  favicon: assets/images/terminal.svg
  features:
    - navigation.tabs
  palette:
    scheme: slate
    primary: deep purple

extra_css:
  - css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.superfences
  - toc:
      permalink: true
