name: clang-format

on: push

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: opzioni
          auto-activate-base: false
          environment-file: environment.yml

      - name: Check header files
        run: clang-format --dry-run --verbose -Werror $(find . -path './subprojects' -prune , -name '*.hpp')

      - name: Check source files
        run: clang-format --dry-run --verbose -Werror $(find . -path './subprojects' -prune , -name '*.cpp')
