name: clang-format

on: push

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: opzioni
          auto-activate-base: false
          environment-file: environment.yml

      - name: Check examples/
        run: clang-format --dry-run --verbose -Werror examples/*.cpp
        if: always()

      - name: Check include/
        run: clang-format --dry-run --verbose -Werror include/*.hpp
        if: always()

      - name: Check src/
        run: clang-format --dry-run --verbose -Werror src/*.cpp
        if: always()

      - name: Check tests/
        run: clang-format --dry-run --verbose -Werror tests/*.cpp
        if: always()
