name: tests

on: push

jobs:
  gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - name: Cache conda packages
        uses: actions/cache@v4
        env:
          CACHE_VERSION: 0
        with:
          path: ~/conda_pkgs_dir
          key: conda-v${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: opzioni
          auto-activate-base: false
          environment-file: environment.yml
          channels: conda-forge
          conda-remove-defaults: true

      - run: make setup-gcc
      - run: make build
      - run: make test
