name: tests

on: push

jobs:
  gcc:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2

      - name: Cache conda packages
        uses: actions/cache@v2
        env:
          CACHE_VERSION: 0
        with:
          path: ~/conda_pkgs_dir
          key: conda-v${{ env.CACHE_VERSION }}-${{ runner.os }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: opzioni
          auto-activate-base: false
          environment-file: environment.yml

      - run: make setup-gcc
      - run: make build
      - run: make test
